### ISSUE TITLE
Polylang language switcher not working for menu

### ISSUE THREAD

**Issue by MatusKnizka** [GratisThemes/Bidnis#1]
Hi, I have problem with polylang language switcher ( https://wordpress.org/plugins/polylang/ ) on m website (Bidnis theme). I set up three languages - EN, DE, SK. Page content works fine, it is switching language, but the problem is with menu - language is still DE. I have created also three menus for every single language. 

Both are up-to-date.

Have you ever seen something similar before ? 
Is polylang compatible with Bidnis theme ?

Thank you.

**Comment by kniffen** [comment]
Seems to work fine when testing it here.

Are you sure you enabled the right checkboxes at the end of the menu settings?
Also the language menu item itself has a few settings.
